services:
  arch:
    image: qemux/qemu
    container_name: omarchy-arch
    environment:
      BOOT: "archlinux-x86_64.iso"
      RAM_SIZE: "${RAM_SIZE:-4G}"
      CPU_CORES: "${CPU_CORES:-4}"
      DISK_SIZE: "${DISK_SIZE:-64G}"
      TZ: "${TZ:-Africa/Tunis}"
      ARGUMENTS: "-device usb-kbd"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8007:8006
      - 127.0.0.1:2222:22
    volumes:
      - ./archlinux-x86_64.iso:/boot.iso
      - ./arch:/storage
      - ./Arch:/shared
    restart: "no"
    stop_grace_period: 2m